
module.exports = {
  options: async (tln, args) => {},
  env: async (tln, env) => {

  },
  dotenvs: async (tln) => ['.env'],
  inherits: async (tln) => [],
  depends: async (tln) => ['kubectl-1.34.3', 'helm-4.1.0', 'terraform-1.14.3', 'azure-cli'],
  steps: async (tln) => [],
  components: async (tln) => []
}
