project:
  id: tln-clouds
  name: Talan Clouds
  description: Cloud Agnostic IaC SaaS skeleton
team:
  vlad.k:
    name: Vladyslav Kurmaz
    email: vladislav.kurmaz@gmail.com
    fte: 0.01
timeline:
  25.4.0:
    deadline: 2025-04-21T18:00:00.000Z
  24.11.0:
    deadline: 2024-11-08 12:00:00 GMT+0200
tasks: |-
  [-:020:25.4.0] Ad shared component with bastion, cognito, dbs #aws @vlad.k
  [-:019:25.4.0] Move Cognito user pool, app, idp to shared area #aws @vlad.k
  [-:018:25.4.0] Add DB instance creation template at Tenant layer #aws @vlad.k
  [+:017:24.11.0] Pin version for cognito_pre_auth_function -> 7.13.0 #aws @vlad.k
  [-:016:25.4.0] Add construct/deconstruct into CI/CD @vlad.k
  [+:015:24.11.0] Bump versions #aws @vlad.k
  [-:014] Add "coming-soon" AWS Amplify at group layer #aws @vlad.k
  [-:013] Add template for db-per-tenant #aws @vlad.k
  [-:012] Add node autoscaler #aws @vlad.k
  [-:011] Add pod autoscaler #aws @vlad.k
  [-:010] Add terraform refresh command @vlad.k
  [-:009] Use provided region to access k8s cluster #aws #bug @vlad.k
  [-:008] Troubleshoot Nginx X-Forwarded-* headers  [](srs/nlb) #aws #bug @vlad.k
  [-:007] Add parameters for maintenance window for RDS #aws @vlad.k
  [-:006] Multiple domains at group layer #aws @vlad.k
  [-:005] .gitsibtrees is not modified if git subtree pull is failed #bug @vlad.k
  [-:004] Wait for k8s to destroy before VPC can be deleted #do @vlad.k
  [-:003] Infrastructure skeleton #gcp @vlad.k
    [-] Resource group, networks, bastion
    [-] K8s
  [-:002] Infrastructure skeleton #azure @vlad.k
    [-] Resource group, networks, bastion
    [-] K8s
  [-:001] Bastion enhancement #do @vlad.k
