apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  selector:
    component: whoami
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      component: whoami
  template:
    metadata:
      labels:
        component: whoami
      annotations:
        rollme: "{{ randAlphaNum 5 | quote }}"
    spec:
      restartPolicy: Always
      containers:
        - name: whoami
          image: traefik/whoami
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-whoami
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  rules:
    - host: "api.umlhub.io"
      http:
        paths:
          - path: "/whoami(/|$)(.*)"
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: whoami
                port:
                  number: 80
  ingressClassName: nginx
