replicaCount: 2

pgbouncer:

# 1. Service for Applications (EKS Service)
service:
  type: ClusterIP
  ports:
    postgresql: 6432

# 2. MONITORING (Optional: for Prometheus/Grafana)
metrics:
  enabled: true