tasks: |-
  [-:013:26.2.0] Extend Postgresql deployment mechanism to the multiple DB VMs #32h @roman.k
    [-] Extend current DB VM JSON configuration, preserving current single DB VM deployment mechanism
    [-] Add read-replicas (master-slaves) configuration
    [-] Add PgBouncer configuration or AWS RDS Proxy configuration for the multiple DB VMs setup
    [-] Extend backup/restore procedure to support multiple DB VMs
  [-:012:26.2.0] Switch to the Postgres 18.x version #4h @roman.k
  [-:011:26.2.0] Add AWS lambda as part of AWS Cognito configuration to inject custom JWT claims #4h @roman.k
  [-:010:26.2.0] Inject X-Forwarded-Proto at NLB level/Nginx level #2h @roman.k
  [-:009:26.2.0] Align nginx ingress configuration according to the latest security requirements #4h @roman.k
  [-:008:26.2.0] Freeze k8s addons versions and bastion VM image vesion #2h @roman.k
  [-:007:26.2.0] ECR cleanup procedure #4h @roman.k
  [-:006:26.2.0] Add access to the cluster via bastion using Wireguard, preserving sshuttle access #8h @roman.k
  [-:005:26.2.0] Update all terraform modules + k8s to the latest versions #16h @roman.k
  [-:004:26.2.0] Review AWS Organisations setup #2h @roman.k
  [-:003:26.2.0] Add bastion disk size parameter #2h @vlad.k
  [-:002:26.2.0] Troubleshoot lgallard/backup/aws@0.23.8 selection issue or downgrade to 0.22.0 version @vlad.k
  [+:001:25.5.0] Bump Cognito configuration @vlad.k
