tasks: |-
  [>:016:26.5.0] Add S3 (public/private) + AWS Lambda for upload notification #8h @taras.o
  [-:015:26.5.0] Add PgBouncer at app layer #24h @taras.o
  [+:014:26.4.0] Bump lgallard/backup/aws module to 1.7.1 version #4h @taras.o
  [-:013:26.5.0] Add CAA DNS record #2h @taras.o
  [>:012:26.5.0] Extend Postgresql deployment mechanism to the multiple DB VMs #32h @roman.k
    [-] Extend current DB VM JSON configuration, preserving current single DB VM deployment mechanism
    [-] Add read-replicas (master-slaves) configuration
    [-] Extend backup/restore procedure to support multiple DB VMs
  [-:011:26.4.0] Add AWS lambda as part of AWS Cognito configuration to inject custom JWT claims #4h @taras.o
  [+:010:26.4.0] Inject X-Forwarded-Proto at NLB level/Nginx level #2h #dropped @vlad.k
  [-:009:26.5.0] Align nginx ingress configuration according to the latest security requirements #4h @taras.o
  [+:008:26.4.0] Freeze k8s addons versions and bastion VM image vesion #2h @vlad.k
  [-:007:26.5.0] ECR cleanup procedure #4h @vlad.k
  [>:006:26.4.0] Add access to the cluster via bastion using Wireguard, preserving sshuttle access #8h @taras.o
  [+:005:26.4.0] Update all terraform modules, versions and k8s to the latest available versions #104h @taras.o
    [+] Provider layer
    [+] Group layer
    [+] Network layer
      [+] VPC
      [+] Bastion EC2
    [+] Managed layer
      [+] EKS
      [+] Node groups
    [+] App layer
      [+] RDS (Postgresql)
      [+] Nginx
      [+] Cognito
    [+] Tenant layer
      [+] Postgresql 18.x
  [+:004:26.4.0] Review AWS Organisations setup #2h @vlad.k
  [-:003:26.5.0] Add bastion disk size parameter #2h @vlad.k
  [+:002:26.4.0] Troubleshoot lgallard/backup/aws@0.23.8 selection issue or downgrade to 0.22.0 version @vlad.k
  [+:001:25.5.0] Bump Cognito configuration @vlad.k
