tasks: |-
  [>:003:25.8.0] Add bastion disk size parameter #2h @vlad.k
  [-:002:25.8.0] Troubleshoot lgallard/backup/aws@0.23.8 selection issue or downgrade to 0.22.0 version @vlad.k
  [+:001:25.5.0] Bump Cognito configuration @vlad.k
